### ISSUE TITLE
Bug Found Regarding Brand Screen

### ISSUE THREAD

**Issue by Ferose7** [StandardTouch0/alhomaidhi_customer_app#10]
@yaseeen96 bro

a new Bug Found - When I am on the home screen & tap on the brand button the brand screen is visible. But, When I am on the product details page & then tap on the brand button the brand screen is not visible.

![WhatsApp Image 2023-12-20 at 13 08 03_ad0dc437](https://github.com/StandardTouch0/alhomaidhi_customer_app/assets/153482564/48e9cafb-8f1a-41c7-a102-a33d8643055c)

**Comment by yaseeen96** [comment]
@Ferose7 Fixed it. Thanks for raising an issue
