### ISSUE TITLE
Logout Redirect Issue

### ISSUE THREAD

**Issue by kahkashanshaik** [StandardTouch0/alhomaidhi_customer_app#12]
@yaseeen96 after logout can we redirect user to login page without OTP screen and empty phone number fields.
<img width="242" alt="Screenshot 2023-12-21 182602" src="https://github.com/StandardTouch0/alhomaidhi_customer_app/assets/93042682/be8f32e2-03a5-4216-95af-b8a9533315ce">

**Comment by yaseeen96** [comment]
Sure. will look into that @kahkashanshaik

**Comment by yaseeen96** [comment]
Fixed it
