### ISSUE TITLE
Remove home icon in my orders screen 

### ISSUE THREAD

**Issue by zaid2229** [StandardTouch0/alhomaidhi_customer_app#15]
as you see in screenshot there are  two icons 
![WhatsApp Image 2024-01-25 at 12 44 02 PM](https://github.com/StandardTouch0/alhomaidhi_customer_app/assets/60132555/200ebe98-8521-4d73-8146-a4745e840330)
one is back icon and home icon both navigate to home screen only .

**Comment by yaseeen96** [comment]
@zaid2229 fjkeunikugrenbikureuibt ghjv b uikrsnbigvb skvb uikjnbsiub gsjk khjs bsuikvk nikiksb i sedv bnuijknd bs uijk b fsdfd
